export const CHANGE_PERIOD = 'CHANGE_PERIOD';
export const CHANGE_CRYPTO_LIST = 'CHANGE_CRYPTO_LIST';
export const CHANGE_CRYPTO_DATA = 'CHANGE_CRYPTO_DATA';
export const CHANGE_CHART_TYPE = 'CHANGE_CHART_TYPE';