export const CHANGE_PERIOD = 'CHANGE_PERIOD';
export const ADD_TO_CRYPTO_LIST = 'ADD_TO_CRYPTO_LIST';
export const DELETE_FROM_CRYPTO_LIST = 'DELETE_FROM_CRYPTO_LIST';
export const ADD_CRYPTO_DATA = 'ADD_CRYPTO_DATA';
export const DELETE_CRYPTO_DATA = 'DELETE_CRYPTO_DATA';
export const CHANGE_CHART_TYPE = 'CHANGE_CHART_TYPE';
